NOTIFICATION_TYPES = {
    "video": "VIDEO_RECOMMENDATION",
    "engagement": "SENTIMENT_ENGAGEMENT",
    "sentiment": "SENTIMENT_QA",
}
FLOW_BY_EVENT_TYPE = {
    "VIDEO_RECOMMENDATION": "performance",
    "SENTIMENT_ENGAGEMENT": "engagement",
    "SENTIMENT_QA": "sentiment",
}
NEXT_NOTIFICATION_BY_EVENT_TYPE = {
    "VIDEO_RECOMMENDATION": "SENTIMENT_ENGAGEMENT",
    "SENTIMENT_ENGAGEMENT": "SENTIMENT_QA",
    "SENTIMENT_QA": "VIDEO_RECOMMENDATION",
}
VIDEO_POPUP = {"video": "Y", "engagement": "N", "sentiment": "N"}
NOTIFICATION_CYCLE = {
    1: "VIDEO_RECOMMENDATION",
    2: "SENTIMENT_ENGAGEMENT",
    3: "SENTIMENT_QA",
    4: "VIDEO_RECOMMENDATION",
    5: "SENTIMENT_ENGAGEMENT",
    6: "SENTIMENT_QA",
    7: None,
}
